# Generated by Django 5.0.4 on 2024-12-29 17:59

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='id',
            field=models.CharField(default=base.models.generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.CharField(default=base.models.generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.CharField(default=base.models.generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.CharField(default=base.models.generate, editable=False, max_length=21, primary_key=True, serialize=False),
        ),
    ]
